### ISSUE TITLE
Historical not working

### ISSUE THREAD

**Issue by SudheendraSoftionik** [s0h3ck/coinpaprika-api-python-client#5]
Hi,

In below code I am requesting data from 18th july but in API it's giving data from 29th july. Why it is giving like that? 

from coinpaprika import client as Coinpaprika
client = Coinpaprika.Client()
range_between_ticker_data = client.historical('cope-cope',start='2021-07-18T21:32:00Z',end='2021-08-05T09:14:56Z',interval='30m')
print(range_between_ticker_data)

**Comment by s0h3ck** [comment]
Hi SudheendraSoftionik, it is likely because coinpaprika does not have the historical data before July 29th. Coinpaprika Team is probably scraping data from other sources or have not yet filled the historical data for this coin. Please understand that coinpaprika-api-python-client is only a wrapper to interact with coinpaprika API. Thanks!
